// AliExpress Supported Countries
// Based on AliExpress Open Platform documentation
export interface AliExpressCountry {
  code: string;
  name: string;
  currency?: string;
  language?: string;
  phone_code?: string;
}

export const ALIEXPRESS_COUNTRIES: AliExpressCountry[] = [
  { code: "US", name: "United States", currency: "USD", language: "en", phone_code: "+1" },
  { code: "CA", name: "Canada", currency: "CAD", language: "en", phone_code: "+1" },
  { code: "UK", name: "United Kingdom", currency: "GBP", language: "en", phone_code: "+44" },
  { code: "AU", name: "Australia", currency: "AUD", language: "en", phone_code: "+61" },
  { code: "DE", name: "Germany", currency: "EUR", language: "de", phone_code: "+49" },
  { code: "FR", name: "France", currency: "EUR", language: "fr", phone_code: "+33" },
  { code: "IT", name: "Italy", currency: "EUR", language: "it", phone_code: "+39" },
  { code: "ES", name: "Spain", currency: "EUR", language: "es", phone_code: "+34" },
  { code: "NL", name: "Netherlands", currency: "EUR", language: "nl", phone_code: "+31" },
  { code: "BE", name: "Belgium", currency: "EUR", language: "nl", phone_code: "+32" },
  { code: "AT", name: "Austria", currency: "EUR", language: "de", phone_code: "+43" },
  { code: "SE", name: "Sweden", currency: "SEK", language: "sv", phone_code: "+46" },
  { code: "NO", name: "Norway", currency: "NOK", language: "no", phone_code: "+47" },
  { code: "DK", name: "Denmark", currency: "DKK", language: "da", phone_code: "+45" },
  { code: "FI", name: "Finland", currency: "EUR", language: "fi", phone_code: "+358" },
  { code: "PL", name: "Poland", currency: "PLN", language: "pl", phone_code: "+48" },
  { code: "CZ", name: "Czech Republic", currency: "CZK", language: "cs", phone_code: "+420" },
  { code: "HU", name: "Hungary", currency: "HUF", language: "hu", phone_code: "+36" },
  { code: "RO", name: "Romania", currency: "RON", language: "ro", phone_code: "+40" },
  { code: "BG", name: "Bulgaria", currency: "BGN", language: "bg", phone_code: "+359" },
  { code: "HR", name: "Croatia", currency: "EUR", language: "hr", phone_code: "+385" },
  { code: "SI", name: "Slovenia", currency: "EUR", language: "sl", phone_code: "+386" },
  { code: "SK", name: "Slovakia", currency: "EUR", language: "sk", phone_code: "+421" },
  { code: "EE", name: "Estonia", currency: "EUR", language: "et", phone_code: "+372" },
  { code: "LV", name: "Latvia", currency: "EUR", language: "lv", phone_code: "+371" },
  { code: "LT", name: "Lithuania", currency: "EUR", language: "lt", phone_code: "+370" },
  { code: "PT", name: "Portugal", currency: "EUR", language: "pt", phone_code: "+351" },
  { code: "IE", name: "Ireland", currency: "EUR", language: "en", phone_code: "+353" },
  { code: "LU", name: "Luxembourg", currency: "EUR", language: "fr", phone_code: "+352" },
  { code: "MT", name: "Malta", currency: "EUR", language: "en", phone_code: "+356" },
  { code: "CY", name: "Cyprus", currency: "EUR", language: "en", phone_code: "+357" },
  { code: "GR", name: "Greece", currency: "EUR", language: "el", phone_code: "+30" },
  { code: "BR", name: "Brazil", currency: "BRL", language: "pt", phone_code: "+55" },
  { code: "MX", name: "Mexico", currency: "MXN", language: "es", phone_code: "+52" },
  { code: "AR", name: "Argentina", currency: "ARS", language: "es", phone_code: "+54" },
  { code: "CL", name: "Chile", currency: "CLP", language: "es", phone_code: "+56" },
  { code: "CO", name: "Colombia", currency: "COP", language: "es", phone_code: "+57" },
  { code: "PE", name: "Peru", currency: "PEN", language: "es", phone_code: "+51" },
  { code: "VE", name: "Venezuela", currency: "VES", language: "es", phone_code: "+58" },
  { code: "UY", name: "Uruguay", currency: "UYU", language: "es", phone_code: "+598" },
  { code: "PY", name: "Paraguay", currency: "PYG", language: "es", phone_code: "+595" },
  { code: "BO", name: "Bolivia", currency: "BOB", language: "es", phone_code: "+591" },
  { code: "EC", name: "Ecuador", currency: "USD", language: "es", phone_code: "+593" },
  { code: "RU", name: "Russia", currency: "RUB", language: "ru", phone_code: "+7" },
  { code: "UA", name: "Ukraine", currency: "UAH", language: "uk", phone_code: "+380" },
  { code: "BY", name: "Belarus", currency: "BYN", language: "be", phone_code: "+375" },
  { code: "MD", name: "Moldova", currency: "MDL", language: "ro", phone_code: "+373" },
  { code: "GE", name: "Georgia", currency: "GEL", language: "ka", phone_code: "+995" },
  { code: "AM", name: "Armenia", currency: "AMD", language: "hy", phone_code: "+374" },
  { code: "AZ", name: "Azerbaijan", currency: "AZN", language: "az", phone_code: "+994" },
  { code: "KZ", name: "Kazakhstan", currency: "KZT", language: "kk", phone_code: "+7" },
  { code: "UZ", name: "Uzbekistan", currency: "UZS", language: "uz", phone_code: "+998" },
  { code: "KG", name: "Kyrgyzstan", currency: "KGS", language: "ky", phone_code: "+996" },
  { code: "TJ", name: "Tajikistan", currency: "TJS", language: "tg", phone_code: "+992" },
  { code: "TM", name: "Turkmenistan", currency: "TMT", language: "tk", phone_code: "+993" },
  { code: "TR", name: "Turkey", currency: "TRY", language: "tr", phone_code: "+90" },
  { code: "IL", name: "Israel", currency: "ILS", language: "he", phone_code: "+972" },
  { code: "SA", name: "Saudi Arabia", currency: "SAR", language: "ar", phone_code: "+966" },
  { code: "AE", name: "United Arab Emirates", currency: "AED", language: "ar", phone_code: "+971" },
  { code: "KW", name: "Kuwait", currency: "KWD", language: "ar", phone_code: "+965" },
  { code: "QA", name: "Qatar", currency: "QAR", language: "ar", phone_code: "+974" },
  { code: "BH", name: "Bahrain", currency: "BHD", language: "ar", phone_code: "+973" },
  { code: "OM", name: "Oman", currency: "OMR", language: "ar", phone_code: "+968" },
  { code: "JO", name: "Jordan", currency: "JOD", language: "ar", phone_code: "+962" },
  { code: "LB", name: "Lebanon", currency: "LBP", language: "ar", phone_code: "+961" },
  { code: "SY", name: "Syria", currency: "SYP", language: "ar", phone_code: "+963" },
  { code: "IQ", name: "Iraq", currency: "IQD", language: "ar", phone_code: "+964" },
  { code: "YE", name: "Yemen", currency: "YER", language: "ar", phone_code: "+967" },
  { code: "EG", name: "Egypt", currency: "EGP", language: "ar", phone_code: "+20" },
  { code: "LY", name: "Libya", currency: "LYD", language: "ar", phone_code: "+218" },
  { code: "TN", name: "Tunisia", currency: "TND", language: "ar", phone_code: "+216" },
  { code: "DZ", name: "Algeria", currency: "DZD", language: "ar", phone_code: "+213" },
  { code: "MA", name: "Morocco", currency: "MAD", language: "ar", phone_code: "+212" },
  { code: "SD", name: "Sudan", currency: "SDG", language: "ar", phone_code: "+249" },
  { code: "SS", name: "South Sudan", currency: "SSP", language: "en", phone_code: "+211" },
  { code: "ET", name: "Ethiopia", currency: "ETB", language: "am", phone_code: "+251" },
  { code: "ER", name: "Eritrea", currency: "ERN", language: "ti", phone_code: "+291" },
  { code: "DJ", name: "Djibouti", currency: "DJF", language: "ar", phone_code: "+253" },
  { code: "SO", name: "Somalia", currency: "SOS", language: "so", phone_code: "+252" },
  { code: "KE", name: "Kenya", currency: "KES", language: "sw", phone_code: "+254" },
  { code: "TZ", name: "Tanzania", currency: "TZS", language: "sw", phone_code: "+255" },
  { code: "UG", name: "Uganda", currency: "UGX", language: "en", phone_code: "+256" },
  { code: "RW", name: "Rwanda", currency: "RWF", language: "rw", phone_code: "+250" },
  { code: "BI", name: "Burundi", currency: "BIF", language: "rn", phone_code: "+257" },
  { code: "MZ", name: "Mozambique", currency: "MZN", language: "pt", phone_code: "+258" },
  { code: "ZW", name: "Zimbabwe", currency: "ZWL", language: "en", phone_code: "+263" },
  { code: "ZM", name: "Zambia", currency: "ZMW", language: "en", phone_code: "+260" },
  { code: "MW", name: "Malawi", currency: "MWK", language: "en", phone_code: "+265" },
  { code: "BW", name: "Botswana", currency: "BWP", language: "en", phone_code: "+267" },
  { code: "NA", name: "Namibia", currency: "NAD", language: "en", phone_code: "+264" },
  { code: "LS", name: "Lesotho", currency: "LSL", language: "en", phone_code: "+266" },
  { code: "SZ", name: "Eswatini", currency: "SZL", language: "en", phone_code: "+268" },
  { code: "ZA", name: "South Africa", currency: "ZAR", language: "en", phone_code: "+27" },
  { code: "MG", name: "Madagascar", currency: "MGA", language: "mg", phone_code: "+261" },
  { code: "MU", name: "Mauritius", currency: "MUR", language: "en", phone_code: "+230" },
  { code: "SC", name: "Seychelles", currency: "SCR", language: "en", phone_code: "+248" },
  { code: "KM", name: "Comoros", currency: "KMF", language: "ar", phone_code: "+269" },
  { code: "CV", name: "Cape Verde", currency: "CVE", language: "pt", phone_code: "+238" },
  { code: "GW", name: "Guinea-Bissau", currency: "XOF", language: "pt", phone_code: "+245" },
  { code: "GN", name: "Guinea", currency: "GNF", language: "fr", phone_code: "+224" },
  { code: "SL", name: "Sierra Leone", currency: "SLL", language: "en", phone_code: "+232" },
  { code: "LR", name: "Liberia", currency: "LRD", language: "en", phone_code: "+231" },
  { code: "CI", name: "Ivory Coast", currency: "XOF", language: "fr", phone_code: "+225" },
  { code: "GH", name: "Ghana", currency: "GHS", language: "en", phone_code: "+233" },
  { code: "TG", name: "Togo", currency: "XOF", language: "fr", phone_code: "+228" },
  { code: "BJ", name: "Benin", currency: "XOF", language: "fr", phone_code: "+229" },
  { code: "NG", name: "Nigeria", currency: "NGN", language: "en", phone_code: "+234" },
  { code: "CM", name: "Cameroon", currency: "XAF", language: "fr", phone_code: "+237" },
  { code: "CF", name: "Central African Republic", currency: "XAF", language: "fr", phone_code: "+236" },
  { code: "TD", name: "Chad", currency: "XAF", language: "ar", phone_code: "+235" },
  { code: "NE", name: "Niger", currency: "XOF", language: "fr", phone_code: "+227" },
  { code: "ML", name: "Mali", currency: "XOF", language: "fr", phone_code: "+223" },
  { code: "BF", name: "Burkina Faso", currency: "XOF", language: "fr", phone_code: "+226" },
  { code: "SN", name: "Senegal", currency: "XOF", language: "fr", phone_code: "+221" },
  { code: "GM", name: "Gambia", currency: "GMD", language: "en", phone_code: "+220" },
  { code: "MR", name: "Mauritania", currency: "MRU", language: "ar", phone_code: "+222" },
  { code: "EH", name: "Western Sahara", currency: "MAD", language: "ar", phone_code: "+212" },
  { code: "IN", name: "India", currency: "INR", language: "hi", phone_code: "+91" },
  { code: "PK", name: "Pakistan", currency: "PKR", language: "ur", phone_code: "+92" },
  { code: "BD", name: "Bangladesh", currency: "BDT", language: "bn", phone_code: "+880" },
  { code: "LK", name: "Sri Lanka", currency: "LKR", language: "si", phone_code: "+94" },
  { code: "NP", name: "Nepal", currency: "NPR", language: "ne", phone_code: "+977" },
  { code: "BT", name: "Bhutan", currency: "BTN", language: "dz", phone_code: "+975" },
  { code: "MV", name: "Maldives", currency: "MVR", language: "dv", phone_code: "+960" },
  { code: "AF", name: "Afghanistan", currency: "AFN", language: "ps", phone_code: "+93" },
  { code: "IR", name: "Iran", currency: "IRR", language: "fa", phone_code: "+98" },
  { code: "CN", name: "China", currency: "CNY", language: "zh", phone_code: "+86" },
  { code: "TW", name: "Taiwan", currency: "TWD", language: "zh", phone_code: "+886" },
  { code: "HK", name: "Hong Kong", currency: "HKD", language: "zh", phone_code: "+852" },
  { code: "MO", name: "Macau", currency: "MOP", language: "zh", phone_code: "+853" },
  { code: "JP", name: "Japan", currency: "JPY", language: "ja", phone_code: "+81" },
  { code: "KR", name: "South Korea", currency: "KRW", language: "ko", phone_code: "+82" },
  { code: "KP", name: "North Korea", currency: "KPW", language: "ko", phone_code: "+850" },
  { code: "VN", name: "Vietnam", currency: "VND", language: "vi", phone_code: "+84" },
  { code: "LA", name: "Laos", currency: "LAK", language: "lo", phone_code: "+856" },
  { code: "KH", name: "Cambodia", currency: "KHR", language: "km", phone_code: "+855" },
  { code: "TH", name: "Thailand", currency: "THB", language: "th", phone_code: "+66" },
  { code: "MM", name: "Myanmar", currency: "MMK", language: "my", phone_code: "+95" },
  { code: "MY", name: "Malaysia", currency: "MYR", language: "ms", phone_code: "+60" },
  { code: "SG", name: "Singapore", currency: "SGD", language: "en", phone_code: "+65" },
  { code: "ID", name: "Indonesia", currency: "IDR", language: "id", phone_code: "+62" },
  { code: "PH", name: "Philippines", currency: "PHP", language: "tl", phone_code: "+63" },
  { code: "BN", name: "Brunei", currency: "BND", language: "ms", phone_code: "+673" },
  { code: "TL", name: "East Timor", currency: "USD", language: "pt", phone_code: "+670" },
  { code: "PG", name: "Papua New Guinea", currency: "PGK", language: "en", phone_code: "+675" },
  { code: "FJ", name: "Fiji", currency: "FJD", language: "en", phone_code: "+679" },
  { code: "NC", name: "New Caledonia", currency: "XPF", language: "fr", phone_code: "+687" },
  { code: "VU", name: "Vanuatu", currency: "VUV", language: "bi", phone_code: "+678" },
  { code: "SB", name: "Solomon Islands", currency: "SBD", language: "en", phone_code: "+677" },
  { code: "TO", name: "Tonga", currency: "TOP", language: "to", phone_code: "+676" },
  { code: "WS", name: "Samoa", currency: "WST", language: "sm", phone_code: "+685" },
  { code: "KI", name: "Kiribati", currency: "AUD", language: "en", phone_code: "+686" },
  { code: "TV", name: "Tuvalu", currency: "AUD", language: "en", phone_code: "+688" },
  { code: "NR", name: "Nauru", currency: "AUD", language: "en", phone_code: "+674" },
  { code: "PW", name: "Palau", currency: "USD", language: "en", phone_code: "+680" },
  { code: "MH", name: "Marshall Islands", currency: "USD", language: "en", phone_code: "+692" },
  { code: "FM", name: "Micronesia", currency: "USD", language: "en", phone_code: "+691" },
  { code: "CK", name: "Cook Islands", currency: "NZD", language: "en", phone_code: "+682" },
  { code: "NU", name: "Niue", currency: "NZD", language: "en", phone_code: "+683" },
  { code: "TK", name: "Tokelau", currency: "NZD", language: "en", phone_code: "+690" },
  { code: "AS", name: "American Samoa", currency: "USD", language: "en", phone_code: "+1" },
  { code: "GU", name: "Guam", currency: "USD", language: "en", phone_code: "+1" },
  { code: "MP", name: "Northern Mariana Islands", currency: "USD", language: "en", phone_code: "+1" },
  { code: "PF", name: "French Polynesia", currency: "XPF", language: "fr", phone_code: "+689" },
  { code: "WF", name: "Wallis and Futuna", currency: "XPF", language: "fr", phone_code: "+681" },
];

// Helper function to get country by code
export const getCountryByCode = (code: string): AliExpressCountry | undefined => {
  return ALIEXPRESS_COUNTRIES.find(country => country.code === code.toUpperCase());
};

// Helper function to get country by name
export const getCountryByName = (name: string): AliExpressCountry | undefined => {
  return ALIEXPRESS_COUNTRIES.find(country => 
    country.name.toLowerCase().includes(name.toLowerCase())
  );
};

// Helper function to search countries
export const searchCountries = (query: string): AliExpressCountry[] => {
  const lowerQuery = query.toLowerCase();
  return ALIEXPRESS_COUNTRIES.filter(country => 
    country.name.toLowerCase().includes(lowerQuery) ||
    country.code.toLowerCase().includes(lowerQuery)
  );
};
