// AliExpress Supported Countries
// Based on AliExpress Open Platform documentation
export interface AliExpressCountry {
  code: string;
  name: string;
  currency?: string;
  language?: string;
}

export const ALIEXPRESS_COUNTRIES: AliExpressCountry[] = [
  { code: "US", name: "United States", currency: "USD", language: "en" },
  { code: "CA", name: "Canada", currency: "CAD", language: "en" },
  { code: "UK", name: "United Kingdom", currency: "GBP", language: "en" },
  { code: "AU", name: "Australia", currency: "AUD", language: "en" },
  { code: "DE", name: "Germany", currency: "EUR", language: "de" },
  { code: "FR", name: "France", currency: "EUR", language: "fr" },
  { code: "IT", name: "Italy", currency: "EUR", language: "it" },
  { code: "ES", name: "Spain", currency: "EUR", language: "es" },
  { code: "NL", name: "Netherlands", currency: "EUR", language: "nl" },
  { code: "BE", name: "Belgium", currency: "EUR", language: "nl" },
  { code: "AT", name: "Austria", currency: "EUR", language: "de" },
  { code: "SE", name: "Sweden", currency: "SEK", language: "sv" },
  { code: "NO", name: "Norway", currency: "NOK", language: "no" },
  { code: "DK", name: "Denmark", currency: "DKK", language: "da" },
  { code: "FI", name: "Finland", currency: "EUR", language: "fi" },
  { code: "PL", name: "Poland", currency: "PLN", language: "pl" },
  { code: "CZ", name: "Czech Republic", currency: "CZK", language: "cs" },
  { code: "HU", name: "Hungary", currency: "HUF", language: "hu" },
  { code: "RO", name: "Romania", currency: "RON", language: "ro" },
  { code: "BG", name: "Bulgaria", currency: "BGN", language: "bg" },
  { code: "HR", name: "Croatia", currency: "EUR", language: "hr" },
  { code: "SI", name: "Slovenia", currency: "EUR", language: "sl" },
  { code: "SK", name: "Slovakia", currency: "EUR", language: "sk" },
  { code: "EE", name: "Estonia", currency: "EUR", language: "et" },
  { code: "LV", name: "Latvia", currency: "EUR", language: "lv" },
  { code: "LT", name: "Lithuania", currency: "EUR", language: "lt" },
  { code: "PT", name: "Portugal", currency: "EUR", language: "pt" },
  { code: "IE", name: "Ireland", currency: "EUR", language: "en" },
  { code: "LU", name: "Luxembourg", currency: "EUR", language: "fr" },
  { code: "MT", name: "Malta", currency: "EUR", language: "en" },
  { code: "CY", name: "Cyprus", currency: "EUR", language: "en" },
  { code: "GR", name: "Greece", currency: "EUR", language: "el" },
  { code: "BR", name: "Brazil", currency: "BRL", language: "pt" },
  { code: "MX", name: "Mexico", currency: "MXN", language: "es" },
  { code: "AR", name: "Argentina", currency: "ARS", language: "es" },
  { code: "CL", name: "Chile", currency: "CLP", language: "es" },
  { code: "CO", name: "Colombia", currency: "COP", language: "es" },
  { code: "PE", name: "Peru", currency: "PEN", language: "es" },
  { code: "VE", name: "Venezuela", currency: "VES", language: "es" },
  { code: "UY", name: "Uruguay", currency: "UYU", language: "es" },
  { code: "PY", name: "Paraguay", currency: "PYG", language: "es" },
  { code: "BO", name: "Bolivia", currency: "BOB", language: "es" },
  { code: "EC", name: "Ecuador", currency: "USD", language: "es" },
  { code: "RU", name: "Russia", currency: "RUB", language: "ru" },
  { code: "UA", name: "Ukraine", currency: "UAH", language: "uk" },
  { code: "BY", name: "Belarus", currency: "BYN", language: "be" },
  { code: "MD", name: "Moldova", currency: "MDL", language: "ro" },
  { code: "GE", name: "Georgia", currency: "GEL", language: "ka" },
  { code: "AM", name: "Armenia", currency: "AMD", language: "hy" },
  { code: "AZ", name: "Azerbaijan", currency: "AZN", language: "az" },
  { code: "KZ", name: "Kazakhstan", currency: "KZT", language: "kk" },
  { code: "UZ", name: "Uzbekistan", currency: "UZS", language: "uz" },
  { code: "KG", name: "Kyrgyzstan", currency: "KGS", language: "ky" },
  { code: "TJ", name: "Tajikistan", currency: "TJS", language: "tg" },
  { code: "TM", name: "Turkmenistan", currency: "TMT", language: "tk" },
  { code: "TR", name: "Turkey", currency: "TRY", language: "tr" },
  { code: "IL", name: "Israel", currency: "ILS", language: "he" },
  { code: "SA", name: "Saudi Arabia", currency: "SAR", language: "ar" },
  { code: "AE", name: "United Arab Emirates", currency: "AED", language: "ar" },
  { code: "KW", name: "Kuwait", currency: "KWD", language: "ar" },
  { code: "QA", name: "Qatar", currency: "QAR", language: "ar" },
  { code: "BH", name: "Bahrain", currency: "BHD", language: "ar" },
  { code: "OM", name: "Oman", currency: "OMR", language: "ar" },
  { code: "JO", name: "Jordan", currency: "JOD", language: "ar" },
  { code: "LB", name: "Lebanon", currency: "LBP", language: "ar" },
  { code: "SY", name: "Syria", currency: "SYP", language: "ar" },
  { code: "IQ", name: "Iraq", currency: "IQD", language: "ar" },
  { code: "YE", name: "Yemen", currency: "YER", language: "ar" },
  { code: "EG", name: "Egypt", currency: "EGP", language: "ar" },
  { code: "LY", name: "Libya", currency: "LYD", language: "ar" },
  { code: "TN", name: "Tunisia", currency: "TND", language: "ar" },
  { code: "DZ", name: "Algeria", currency: "DZD", language: "ar" },
  { code: "MA", name: "Morocco", currency: "MAD", language: "ar" },
  { code: "SD", name: "Sudan", currency: "SDG", language: "ar" },
  { code: "SS", name: "South Sudan", currency: "SSP", language: "en" },
  { code: "ET", name: "Ethiopia", currency: "ETB", language: "am" },
  { code: "ER", name: "Eritrea", currency: "ERN", language: "ti" },
  { code: "DJ", name: "Djibouti", currency: "DJF", language: "ar" },
  { code: "SO", name: "Somalia", currency: "SOS", language: "so" },
  { code: "KE", name: "Kenya", currency: "KES", language: "sw" },
  { code: "TZ", name: "Tanzania", currency: "TZS", language: "sw" },
  { code: "UG", name: "Uganda", currency: "UGX", language: "en" },
  { code: "RW", name: "Rwanda", currency: "RWF", language: "rw" },
  { code: "BI", name: "Burundi", currency: "BIF", language: "rn" },
  { code: "MZ", name: "Mozambique", currency: "MZN", language: "pt" },
  { code: "ZW", name: "Zimbabwe", currency: "ZWL", language: "en" },
  { code: "ZM", name: "Zambia", currency: "ZMW", language: "en" },
  { code: "MW", name: "Malawi", currency: "MWK", language: "en" },
  { code: "BW", name: "Botswana", currency: "BWP", language: "en" },
  { code: "NA", name: "Namibia", currency: "NAD", language: "en" },
  { code: "LS", name: "Lesotho", currency: "LSL", language: "en" },
  { code: "SZ", name: "Eswatini", currency: "SZL", language: "en" },
  { code: "ZA", name: "South Africa", currency: "ZAR", language: "en" },
  { code: "MG", name: "Madagascar", currency: "MGA", language: "mg" },
  { code: "MU", name: "Mauritius", currency: "MUR", language: "en" },
  { code: "SC", name: "Seychelles", currency: "SCR", language: "en" },
  { code: "KM", name: "Comoros", currency: "KMF", language: "ar" },
  { code: "CV", name: "Cape Verde", currency: "CVE", language: "pt" },
  { code: "GW", name: "Guinea-Bissau", currency: "XOF", language: "pt" },
  { code: "GN", name: "Guinea", currency: "GNF", language: "fr" },
  { code: "SL", name: "Sierra Leone", currency: "SLL", language: "en" },
  { code: "LR", name: "Liberia", currency: "LRD", language: "en" },
  { code: "CI", name: "Ivory Coast", currency: "XOF", language: "fr" },
  { code: "GH", name: "Ghana", currency: "GHS", language: "en" },
  { code: "TG", name: "Togo", currency: "XOF", language: "fr" },
  { code: "BJ", name: "Benin", currency: "XOF", language: "fr" },
  { code: "NG", name: "Nigeria", currency: "NGN", language: "en" },
  { code: "CM", name: "Cameroon", currency: "XAF", language: "fr" },
  { code: "CF", name: "Central African Republic", currency: "XAF", language: "fr" },
  { code: "TD", name: "Chad", currency: "XAF", language: "ar" },
  { code: "NE", name: "Niger", currency: "XOF", language: "fr" },
  { code: "ML", name: "Mali", currency: "XOF", language: "fr" },
  { code: "BF", name: "Burkina Faso", currency: "XOF", language: "fr" },
  { code: "SN", name: "Senegal", currency: "XOF", language: "fr" },
  { code: "GM", name: "Gambia", currency: "GMD", language: "en" },
  { code: "MR", name: "Mauritania", currency: "MRU", language: "ar" },
  { code: "EH", name: "Western Sahara", currency: "MAD", language: "ar" },
  { code: "IN", name: "India", currency: "INR", language: "hi" },
  { code: "PK", name: "Pakistan", currency: "PKR", language: "ur" },
  { code: "BD", name: "Bangladesh", currency: "BDT", language: "bn" },
  { code: "LK", name: "Sri Lanka", currency: "LKR", language: "si" },
  { code: "NP", name: "Nepal", currency: "NPR", language: "ne" },
  { code: "BT", name: "Bhutan", currency: "BTN", language: "dz" },
  { code: "MV", name: "Maldives", currency: "MVR", language: "dv" },
  { code: "AF", name: "Afghanistan", currency: "AFN", language: "ps" },
  { code: "IR", name: "Iran", currency: "IRR", language: "fa" },
  { code: "CN", name: "China", currency: "CNY", language: "zh" },
  { code: "TW", name: "Taiwan", currency: "TWD", language: "zh" },
  { code: "HK", name: "Hong Kong", currency: "HKD", language: "zh" },
  { code: "MO", name: "Macau", currency: "MOP", language: "zh" },
  { code: "JP", name: "Japan", currency: "JPY", language: "ja" },
  { code: "KR", name: "South Korea", currency: "KRW", language: "ko" },
  { code: "KP", name: "North Korea", currency: "KPW", language: "ko" },
  { code: "VN", name: "Vietnam", currency: "VND", language: "vi" },
  { code: "LA", name: "Laos", currency: "LAK", language: "lo" },
  { code: "KH", name: "Cambodia", currency: "KHR", language: "km" },
  { code: "TH", name: "Thailand", currency: "THB", language: "th" },
  { code: "MM", name: "Myanmar", currency: "MMK", language: "my" },
  { code: "MY", name: "Malaysia", currency: "MYR", language: "ms" },
  { code: "SG", name: "Singapore", currency: "SGD", language: "en" },
  { code: "ID", name: "Indonesia", currency: "IDR", language: "id" },
  { code: "PH", name: "Philippines", currency: "PHP", language: "tl" },
  { code: "BN", name: "Brunei", currency: "BND", language: "ms" },
  { code: "TL", name: "East Timor", currency: "USD", language: "pt" },
  { code: "PG", name: "Papua New Guinea", currency: "PGK", language: "en" },
  { code: "FJ", name: "Fiji", currency: "FJD", language: "en" },
  { code: "NC", name: "New Caledonia", currency: "XPF", language: "fr" },
  { code: "VU", name: "Vanuatu", currency: "VUV", language: "bi" },
  { code: "SB", name: "Solomon Islands", currency: "SBD", language: "en" },
  { code: "TO", name: "Tonga", currency: "TOP", language: "to" },
  { code: "WS", name: "Samoa", currency: "WST", language: "sm" },
  { code: "KI", name: "Kiribati", currency: "AUD", language: "en" },
  { code: "TV", name: "Tuvalu", currency: "AUD", language: "en" },
  { code: "NR", name: "Nauru", currency: "AUD", language: "en" },
  { code: "PW", name: "Palau", currency: "USD", language: "en" },
  { code: "MH", name: "Marshall Islands", currency: "USD", language: "en" },
  { code: "FM", name: "Micronesia", currency: "USD", language: "en" },
  { code: "CK", name: "Cook Islands", currency: "NZD", language: "en" },
  { code: "NU", name: "Niue", currency: "NZD", language: "en" },
  { code: "TK", name: "Tokelau", currency: "NZD", language: "en" },
  { code: "AS", name: "American Samoa", currency: "USD", language: "en" },
  { code: "GU", name: "Guam", currency: "USD", language: "en" },
  { code: "MP", name: "Northern Mariana Islands", currency: "USD", language: "en" },
  { code: "PF", name: "French Polynesia", currency: "XPF", language: "fr" },
  { code: "WF", name: "Wallis and Futuna", currency: "XPF", language: "fr" },
];

// Helper function to get country by code
export const getCountryByCode = (code: string): AliExpressCountry | undefined => {
  return ALIEXPRESS_COUNTRIES.find(country => country.code === code.toUpperCase());
};

// Helper function to get country by name
export const getCountryByName = (name: string): AliExpressCountry | undefined => {
  return ALIEXPRESS_COUNTRIES.find(country => 
    country.name.toLowerCase().includes(name.toLowerCase())
  );
};

// Helper function to search countries
export const searchCountries = (query: string): AliExpressCountry[] => {
  const lowerQuery = query.toLowerCase();
  return ALIEXPRESS_COUNTRIES.filter(country => 
    country.name.toLowerCase().includes(lowerQuery) ||
    country.code.toLowerCase().includes(lowerQuery)
  );
};
